/** Shape of `network.json`, generated by `scripts/fetch-network.ts`. */

export type LineId =
  | 'bakerloo'
  | 'central'
  | 'circle'
  | 'district'
  | 'hammersmith-city'
  | 'jubilee'
  | 'metropolitan'
  | 'northern'
  | 'piccadilly'
  | 'victoria'
  | 'waterloo-city'
  | 'dlr'
  | 'elizabeth'

export type Mode = 'tube' | 'dlr' | 'elizabeth-line'

/** Slug derived from the display name, e.g. `kings-cross-st-pancras`. */
export type StationId = string

export interface Station {
  id: StationId
  /** Passenger-facing name — this is what the player types. */
  name: string
  lines: LineId[]
  /** Travel zone as TfL reports it; boundary stations look like `2+3` or `2/3`. */
  zone: string | null
  lat: number
  lon: number
  /** Every NaPTAN id merged into this station (a hub can have tube + DLR + rail ids). */
  naptanIds: string[]
}

/** One end-to-end run along a line, e.g. `High Barnet ↔ Morden via Bank`. */
export interface Route {
  id: string
  label: string
  stationIds: StationId[]
}

/**
 * A line as stored in `network.json` — structure only.
 * Colours deliberately live outside the generated data, in `lineColors.ts`.
 */
export interface LineData {
  id: LineId
  name: string
  mode: Mode
  /** Ordered end-to-end routes, longest first. Used by Line Run. */
  routes: Route[]
  /** Present only where the line has a true circular service (the Circle line). */
  loop: Route | null
}

/** A line as the app sees it: structure plus presentation, merged at load. */
export interface Line extends LineData {
  /** Resolved for the current colour scheme — see `lineColors.ts`. */
  color: string
  /** True when the colour is too light for hairlines or text. */
  lightColor: boolean
  short: string
}

export interface Network {
  version: number
  generatedAt: string
  source: string
  attribution: string
  lines: LineData[]
  stations: Record<StationId, Station>
}
